[build]
    publish = "public"
    command = "hugo"

[context.production.environment]
    HUGO_VERSION = "0.80.0"
    NODE_VERSION = "18.17.1"
    NPM_VERSION = "9.6.7"

[context.deploy-preview]
    command = "hugo --buildDrafts --buildFuture"

[context.branch-deploy]
    command = "hugo --buildDrafts --buildFuture"

[context.next.environment]
    HUGO_ENABLEGITINFO = "true"
    NODE_VERSION = "18.17.1"
    NPM_VERSION = "9.6.7"